// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASL_qJVZkfJTX10XSBoO1i8IxaoqJONks',
    appId: '1:883812930744:web:f2c084ef4dbe0825e2904d',
    messagingSenderId: '883812930744',
    projectId: 'chat-app-2b76a',
    authDomain: 'chat-app-2b76a.firebaseapp.com',
    storageBucket: 'chat-app-2b76a.appspot.com',
    measurementId: 'G-TNCMHQT3MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSqN-pucib4n8DaVoBXQCDa5qngBzynU',
    appId: '1:883812930744:android:8cf702bd7de5e11fe2904d',
    messagingSenderId: '883812930744',
    projectId: 'chat-app-2b76a',
    storageBucket: 'chat-app-2b76a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3j4-0XUmZwm6XTqT1nW1ryrsI6aBAHHI',
    appId: '1:883812930744:ios:985389e7bb12257fe2904d',
    messagingSenderId: '883812930744',
    projectId: 'chat-app-2b76a',
    storageBucket: 'chat-app-2b76a.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3j4-0XUmZwm6XTqT1nW1ryrsI6aBAHHI',
    appId: '1:883812930744:ios:2944883658e318e7e2904d',
    messagingSenderId: '883812930744',
    projectId: 'chat-app-2b76a',
    storageBucket: 'chat-app-2b76a.appspot.com',
    iosBundleId: 'com.example.myChatApp.RunnerTests',
  );
}
